import { Geist, Geist_Mono } from "next/font/google";
import { TubelightNavbar } from "@/components/ui/tubelight-navbar";
import { Footer } from '@/components/ui/footer';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950 text-white min-h-screen`}
      >
        <TubelightNavbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
